apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: almaher-frontend-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Almaher-QTech/QTech-React.git
    targetRevision: config
    path: manifest
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: false